import sys
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
# Ensure we load the local 'elite' package from 'eliterobot' folder
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'eliterobot'))

from elite import EC

# Initialize robot
arm = EC(sim=True)

# 1. Load the calibration matrix generated by handEye.py
arm.load_hand_eye_calibration("hand_eye_result.csv")

# 2. Convert a pixel (u=320, v=240) with depth 0.5m to robot base coordinates
# Intrinsic matrix example (fx, fy, cx, cy)
intrinsic = [600, 0, 320,
             0, 600, 240,
             0, 0, 1]

# eye_in_hand=True will automatically use the robot's current pose
base_coords = arm.pixel_to_base(u=320, v=240, z_depth=0.5,
                                intrinsic_matrix=intrinsic,
                                eye_in_hand=True)

print(f"Target Base Coordinates: {base_coords}")
